# Generated by Django 5.2.1 on 2025-06-02 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='password',
        ),
    ]
