services:
  web:
    build: .
    container_name: tgshopadmin-web
    restart: always
    depends_on:
      - nginx
    environment:
      PG_DATABASE: ${PG_DATABASE}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_HOST: postgres
    volumes:
      - .:/app
    networks:
      - projects-network
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:stable-alpine
    container_name: tgshopadmin-nginx
    restart: always
    ports:
      - "8085:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
      - ./media:/app/media
    networks:
      - projects-network

networks:
  projects-network:
    name: projects-network
    external: true
